// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBpkTTfyIRjz5Af4FWmeRSHCJbDPTo5mOU',
    appId: '1:750836179455:web:a6e6f8cb3bd3221a7287ca',
    messagingSenderId: '750836179455',
    projectId: 't-pop-ea382',
    authDomain: 't-pop-ea382.firebaseapp.com',
    storageBucket: 't-pop-ea382.firebasestorage.app',
    measurementId: 'G-K1E4JZ69X9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAjPY6SB4PhtIDCvLykmzW7H8hdVp83uZM',
    appId: '1:750836179455:android:752538c65d451b907287ca',
    messagingSenderId: '750836179455',
    projectId: 't-pop-ea382',
    storageBucket: 't-pop-ea382.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB0Axv0QYjehEYxJSJlM95zQ958LNG2H-Q',
    appId: '1:750836179455:ios:810e4bef546a8e987287ca',
    messagingSenderId: '750836179455',
    projectId: 't-pop-ea382',
    storageBucket: 't-pop-ea382.firebasestorage.app',
    iosClientId: '750836179455-4po0iuejhvpku84n05jhpd4she9jqssq.apps.googleusercontent.com',
    iosBundleId: 'com.example.appTpop',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB0Axv0QYjehEYxJSJlM95zQ958LNG2H-Q',
    appId: '1:750836179455:ios:810e4bef546a8e987287ca',
    messagingSenderId: '750836179455',
    projectId: 't-pop-ea382',
    storageBucket: 't-pop-ea382.firebasestorage.app',
    iosClientId: '750836179455-4po0iuejhvpku84n05jhpd4she9jqssq.apps.googleusercontent.com',
    iosBundleId: 'com.example.appTpop',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBpkTTfyIRjz5Af4FWmeRSHCJbDPTo5mOU',
    appId: '1:750836179455:web:843519b3a6503d917287ca',
    messagingSenderId: '750836179455',
    projectId: 't-pop-ea382',
    authDomain: 't-pop-ea382.firebaseapp.com',
    storageBucket: 't-pop-ea382.firebasestorage.app',
    measurementId: 'G-W0KBS93F6D',
  );
}
